const sampleData = [
  "The meetings help everyone stay aligned.",
  "The updates are helpful, but sometimes feel repetitive.",
  "I wish there were fewer meetings so I could focus more.",
  "The team meetings keep me motivated and on track.",
  "My work feels meaningful.",
  "Helping others makes me happy with my job.",
  "It seems like meetings take up too much of the day.",
  "I don’t always feel recognized for the effort I put in.",
  "The team is amazing to work with!",
  "I could use a bit more support on projects.",
  "The planning meetings set the tone for my week.",
  "My coworkers make work enjoyable.",
  "I wish the pay reflected the effort we put in.",
  "I would love more recognition for my work.",
  "I feel proud of what we accomplish together.",
  "I appreciate the structure that weekly updates provide.",
  "Work can feel overwhelming at times.",
  "It’s exhausting to keep up with everything some days.",
  "Helping people gives me a sense of purpose.",
  "I sometimes wonder if well-being is a priority.",
  "I feel lucky to have job security here.",
  "It can be hard to stay motivated during busy weeks.",
  "I like our one-on-one meetings; it’s a chance to address issues.",
  "I enjoy the feedback we get—it’s constructive.",
  "I wish the workload wasn’t so intense.",
  "I feel like my contributions could be acknowledged more.",
  "I’m grateful for the flexibility this job provides.",
  "The goals we set help me stay focused.",
  "Sometimes the workload can feel heavy.",
  "Team meetings are helpful, but they can be long.",
  "I enjoy open discussions where ideas are shared.",
  "The team really helps keep me motivated.",
  "Project updates are a good idea, but they could be shorter.",
  "I feel a strong sense of purpose here.",
  "My team is supportive, which makes a difference.",
  "Planning sessions help me stay organized.",
  "It’s nice to work with people who are dedicated.",
  "There are so many meetings—it’s hard to keep up.",
  "The regular updates are useful, but not always necessary.",
  "Long hours of meetings can be exhausting.",
  "I appreciate the open conversations we have as a team.",
  "The planning keeps me on track, but could be more concise.",
  "I enjoy working with a team that’s so motivated.",
  "Sometimes it feels like we meet for the sake of it.",
  "The regular check-ins help me feel connected.",
  "I love working on projects with everyone’s input.",
  "Team meetings are motivating, but a bit formal at times.",
  "Helping people is my favorite part of the job.",
  "The team’s energy makes work enjoyable.",
].join(" ");

export { sampleData };
